AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  EnabledByDefault: true
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - db/**/*

Lint/ConstantResolution:
  Enabled: false

Style/Copyright:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/StringHashKeys:
  Exclude:
    - config/rack_attack.rb

Style/TopLevelMethodDefinition:
  Exclude:
    - bin/**/*

Metrics/AbcSize:
  Exclude:
    - bin/**/*

Metrics/MethodLength:
  Exclude:
    - bin/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - app/routes/**/*.rb
